import Head from "next/head"
// import About from "../components/About"
// import Floats from "../components/Floats"
import Hero from "../components/Hero"
import Navbar from "../components/Navbar"
import Skills from "../components/Skills"

export default function Home() {
  return (
    <>
      <Head>
        <title>Tushar Rajput</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-6 md:px-[10%]">
        <Navbar />
        <Hero />
        {/* <Floats className="fixed" /> */}
        {/* <About /> */}
        <Skills />
      </main>
    </>
  )
}
