import Head from "next/head"
import { useState } from "react"
import Contact from "../components/Contact"
import Hero from "../components/Hero"
import Navbar from "../components/Navbar"
import Projects from "../components/Projects"
import Skills from "../components/Skills"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <>
      <Head>
        <title>Tushar Rajput</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-6 md:px-[10%]">
        <Navbar mode={darkMode} modeFn={setDarkMode} />
        <Hero />
        {/* <Floats className="fixed" /> */}
        {/* <About /> */}
        <Projects />
        <Skills />
        <Contact />
      </main>
    </>
  )
}
